name: Debug Build

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: First Run
        run: echo "$APP_NAME $CURRENTVERSION"
